Repository Dimensionfall/Dimensionfall, pull requests merged in 2024-11, with the labels that each got.

#464 Radio tower furniture
  ItemProtosets.tres
  Mods/Core/Furniture/Furniture.json
  Mods/Core/Furniture/equipmentrack_100_46.png
  Mods/Core/Furniture/equipmentrack_100_46.png.import
  Mods/Core/Furniture/first_aid_rack_72_46.png
  Mods/Core/Furniture/first_aid_rack_72_46.png.import
  Mods/Core/Furniture/transformer_box_72_46.png
  Mods/Core/Furniture/transformer_box_72_46.png.import
  Mods/Core/Furniture/ups_20_45.png
  Mods/Core/Furniture/ups_20_45.png.import
  Mods/Core/Itemgroups/Itemgroups.json
  Mods/Core/Items/Items.json
  Mods/Core/Maps/radio_tower.json
  README.md
  Scripts/Gamedata/DFurniture.gd
  Scripts/Gamedata/DFurnitures.gd
  Scripts/Gamedata/DItemgroups.gd
Labels: enhancement

#469 Transfer inventory item on doubleclick
  Scripts/CtrlInventoryStackedCustom.gd
  Scripts/InventoryWindow.gd
Labels: enhancement

#470 Map guide
  ItemProtosets.tres
  Mods/Core/Itemgroups/Itemgroups.json
  Mods/Core/Items/Items.json
  Mods/Core/Maps/RockyHill_SW.json
  Mods/Core/Mobs/Mobs.json
  Mods/Core/Quests/Quests.json
  Scenes/ContentManager/Custom_Editors/Scripts/QuestEditor.gd
  Scenes/Overmap/Scripts/Overmap.gd
  Scripts/Gamedata/DMob.gd
  Scripts/Helper/overmap_manager.gd
  Scripts/Helper/quest_helper.gd
  Scripts/OvermapGrid.gd
  Scripts/QuestTrackerUI.gd
Labels: enhancement

#474 Added basic "kill zombies" mission via in-game content manager.
  ItemProtosets.tres
  Mods/Core/Items/Items.json
  Mods/Core/Mobs/Mobs.json
  Mods/Core/Quests/Quests.json
Labels: enhancement

#476 Fixed a bug where pressing "return to main menu" multiple times leads to a crash in game over scene.
  Scripts/GameOver.gd
Labels: bug

#472 Add test environment
  Scenes/ContentManager/Mapeditor/Scripts/GridContainer.gd
  Scenes/ContentManager/Mapeditor/mapeditor.tscn
  Scripts/Chunk.gd
  Scripts/Helper.gd
  Scripts/player.gd
  test_environment.gd
  test_environment.tscn
Labels: enhancement

#475 Spawn tacticalmaps outside radius from start position
  Mods/Core/Maps/Generichouse_00.json
  Mods/Core/Maps/neighborhood_school.json
  Mods/Core/Maps/radio_tower.json
  Mods/Core/Maps/two_story_house.json
  Scripts/OvermapGrid.gd
Labels: enhancement

#479 Add Mob groups to quest
  ItemProtosets.tres
  Mods/Core/Mobgroups/Mobgroups.json
  Mods/Core/Mobs/Mobs.json
  Mods/Core/Quests/Quests.json
  Scenes/ContentManager/Custom_Editors/MobgroupsEditor.tscn
  Scenes/ContentManager/Custom_Editors/Scripts/MobgroupsEditor.gd
  Scenes/ContentManager/Custom_Editors/Scripts/QuestEditor.gd
  Scenes/ContentManager/Scripts/contenteditor.gd
  Scenes/ContentManager/contenteditor.tscn
  Scripts/Gamedata/DMobgroup.gd
  Scripts/Gamedata/DMobgroups.gd
  Scripts/Gamedata/DQuest.gd
  Scripts/Helper/quest_helper.gd
  Scripts/QuestTrackerUI.gd
  Scripts/QuestWindow.gd
  Scripts/gamedata.gd
Labels: enhancement

#484 Added a basic scrollbar to the quest rewards' section in the quest list.
  Scenes/UI/QuestWindow.tscn
Labels: enhancement

#482 Add police station and quest step
  ItemProtosets.tres
  Mods/Core/Furniture/Furniture.json
  Mods/Core/Itemgroups/Itemgroups.json
  Mods/Core/Items/Items.json
  Mods/Core/Maps/police_station.json
  Mods/Core/Maps/police_station.png
  Mods/Core/Maps/police_station.png.import
  Mods/Core/Maps/skyscraper.json
  Mods/Core/Mobs/Mobs.json
  Mods/Core/Overmapareas/Overmapareas.json
  Mods/Core/Quests/Quests.json
  Mods/Core/Tiles/Tiles.json
Labels: enhancement

#486 Updated "Kill zombies" mission.
  Mods/Core/Mobgroups/Mobgroups.json
  Mods/Core/Mobs/Mobs.json
  Mods/Core/Quests/Quests.json
Labels: enhancement

#487 Added a new mob group for the robots.
  Mods/Core/Mobgroups/Mobgroups.json
  Mods/Core/Mobs/Mobs.json
Labels: enhancement

#483 Unload chunk after test
  test_environment.gd
  test_environment.tscn
Labels: bug

#485 Zombie loot group
  ItemProtosets.tres
  Mods/Core/Itemgroups/Itemgroups.json
  Mods/Core/Items/Items.json
  Mods/Core/Items/rotten_flesh_chunk_32.png
  Mods/Core/Items/rotten_flesh_chunk_32.png.import
  Mods/Core/Items/wallet_32.png
  Mods/Core/Items/wallet_32.png.import
  Mods/Core/Items/watch_32.png
  Mods/Core/Items/watch_32.png.import
  Mods/Core/Items/zombie_bone_32.png
  Mods/Core/Items/zombie_bone_32.png.import
  Mods/Core/Items/zombie_eye_32.png
  Mods/Core/Items/zombie_eye_32.png.import
  Mods/Core/Items/zombie_organ_32.png
  Mods/Core/Items/zombie_organ_32.png.import
  Mods/Core/Mobs/Mobs.json
  Mods/Core/PlayerAttributes/PlayerAttributes.json
  Mods/Core/Wearableslots/Wearableslots.json
  Scripts/ItemWearableEditor.gd
Labels: enhancement

#488 Spawn mob group
  Mods/Core/Maps/urbanroad.json
  Mods/Core/Mobgroups/Mobgroups.json
  Mods/Core/Mobs/Mobs.json
  Scenes/ContentManager/Mapeditor/Scripts/GridContainer.gd
  Scenes/ContentManager/Mapeditor/Scripts/TilebrushList.gd
  Scenes/ContentManager/Mapeditor/Scripts/mapeditor_brushcomposer.gd
  Scenes/ContentManager/Mapeditor/Scripts/mapeditortile.gd
  Scenes/ContentManager/Mapeditor/Scripts/tilebrush.gd
  Scenes/ContentManager/Mapeditor/tilebrush.tscn
  Scripts/Chunk.gd
  Scripts/Gamedata/DMap.gd
  Scripts/Gamedata/DMobgroup.gd
  Scripts/Gamedata/DQuest.gd
  Scripts/Gamedata/DQuests.gd
  Scripts/Helper/map_manager.gd
Labels: enhancement

#489 Fix despawn containers
  Scripts/Chunk.gd
  Scripts/Gamedata/DMobgroup.gd
  Scripts/container.gd
Labels: bug

#490 Add default_mode to sort to fix healing bug
  Scripts/player.gd
Labels: bug

#491 Add charcoal and kindle and wood bundle
  ItemProtosets.tres
  Mods/Core/Items/Items.json
  Mods/Core/Items/charcoal_chunk_32.png
  Mods/Core/Items/charcoal_chunk_32.png.import
  Mods/Core/Items/kindling_bundle_32.png
  Mods/Core/Items/kindling_bundle_32.png.import
  Scripts/Gamedata/DItems.gd
  Scripts/ItemEditor.gd
Labels: enhancement

#497 Add time progression and a clock
  Scripts/Helper.gd
  Scripts/Helper/save_helper.gd
  Scripts/Helper/time_helper.gd
  Scripts/hud.gd
  hud.tscn
Labels: enhancement

#502 Updated readme.md
  Media/Dimensionfall_mobgroup_editor.png
  Media/desktop.ini
  README.md
Labels: documentation

#500 Add time helper to game architecture document
  Documentation/Game_design/Game_architecture.md
Labels: documentation

#504 Day-night cycle 1.0
  Scripts/Helper/time_helper.gd
  day_night.gd
  day_night.tscn
  front_light.gd
  level_generation.tscn
Labels: enhancement
