Repository Dimensionfall/Dimensionfall, pull requests merged in 2024-06, with the labels that each got.

#188 Misc container/furniture fixes
  LevelGenerator.gd
  Scripts/Chunk.gd
  Scripts/FurniturePhysics.gd
  Scripts/container.gd
  Scripts/item_manager.gd
Labels: bug

#198 Fix startup when no load file is provided
  Scenes/Overmap/Scripts/Overmap.gd
  Scripts/Helper/save_helper.gd
  Scripts/scene_selector.gd
  scene_selector.tscn
Labels: bug

#197 Refactor player skills, add xp
  Scripts/CharacterWindow.gd
  Scripts/player.gd
Labels: enhancement

#190 Add tacticalmap brush label
  Scenes/ContentManager/Custom_Editors/TacticalMapEditor/Scripts/EntitiesContainer.gd
  Scenes/ContentManager/Custom_Editors/TacticalMapEditor/Scripts/TacticalMapEditorTileBrush.gd
  Scenes/ContentManager/Custom_Editors/TacticalMapEditor/TacticalMapEditorTileBrush.tscn
Labels: enhancement

#200 Containers update when game is loaded
  Scripts/FurnitureStatic.gd
  Scripts/container.gd
Labels: bug

#201 Ranged skills
  ItemProtosets.tres
  Mods/Core/Items/Items.json
  Mods/Core/Skills/Skills.json
  Scenes/ContentManager/Custom_Editors/ItemEditor/ItemRangedEditor.tscn
  Scripts/EquippedItem.gd
  Scripts/Helper/json_helper.gd
  Scripts/ItemRangedEditor.gd
  Scripts/gamedata.gd
  level_generation.tscn
Labels: enhancement

#203 Custom tile brush composer for the mapeditor
  Scenes/ContentManager/Custom_Widgets/Scripts/Scrolling_Flow_Container.gd
  Scenes/ContentManager/Mapeditor/Scripts/GridContainer.gd
  Scenes/ContentManager/Mapeditor/Scripts/TilebrushList.gd
  Scenes/ContentManager/Mapeditor/Scripts/mapeditor.gd
  Scenes/ContentManager/Mapeditor/Scripts/mapeditor_brushcomposer.gd
  Scenes/ContentManager/Mapeditor/Scripts/mapeditortile.gd
  Scenes/ContentManager/Mapeditor/Scripts/tilebrush.gd
  Scenes/ContentManager/Mapeditor/mapeditor.tscn
  Scenes/ContentManager/Mapeditor/mapeditor_brushcomposer.tscn
Labels: enhancement

#204 Items can be opened only once in the contenteditor
  Scenes/ContentManager/Scripts/contenteditor.gd
Labels: enhancement

#205 Reduce margin on object detection in chunk
  Scripts/Chunk.gd
Labels: bug

#209 Update readme
  Media/Catax_basic.png
  Media/Catax_crafting_editor.png
  Media/Catax_furniture_editor.png
  Media/Catax_inventory.png
  Media/Catax_map_editor.png
  Media/Catax_skills_editor.png
  Media/Catax_skills_editor.png.import
  Media/Catax_stats_editor.png
  Media/Catax_stats_editor.png.import
  Media/Catax_tacticalmap_editor.png
  README.md
Labels: documentation

#210 Add 11 new furniture and fridge itemgroup
  Mods/Core/Furniture/Furniture.json
  Mods/Core/Furniture/bathtub_100_50.png
  Mods/Core/Furniture/bathtub_100_50.png.import
  Mods/Core/Furniture/bench_garden_90_40.png
  Mods/Core/Furniture/bench_garden_90_40.png.import
  Mods/Core/Furniture/chair_office_50.png
  Mods/Core/Furniture/chair_office_50.png.import
  Mods/Core/Furniture/desk_100_50.png
  Mods/Core/Furniture/desk_100_50.png.import
  Mods/Core/Furniture/lamp_50.png
  Mods/Core/Furniture/lamp_50.png.import
  Mods/Core/Furniture/sofa_100_50.png
  Mods/Core/Furniture/sofa_100_50.png.import
  Mods/Core/Furniture/standing_mirror_50.png
  Mods/Core/Furniture/standing_mirror_50.png.import
  Mods/Core/Furniture/stove_50_48.png
  Mods/Core/Furniture/stove_50_48.png.import
  Mods/Core/Furniture/table_metal_100_50.png
  Mods/Core/Furniture/table_metal_100_50.png.import
  Mods/Core/Furniture/table_picknic_100_50.png
  Mods/Core/Furniture/table_picknic_100_50.png.import
  Mods/Core/Furniture/wardrobe_80_40.png
  Mods/Core/Furniture/wardrobe_80_40.png.import
  Mods/Core/Itemgroups/Itemgroups.json
  Mods/Core/Items/Items.json
  Mods/Core/Maps/Generichouse.json
  Mods/Core/Maps/Generichouse_00.json
  Scenes/ContentManager/Custom_Editors/ItemgroupEditor.tscn
Labels: enhancement

#212 Container sprite fix
  Scripts/Chunk.gd
  Scripts/FurniturePhysics.gd
  Scripts/FurnitureStatic.gd
  Scripts/Mob.gd
  Scripts/container.gd
Labels: bug

#213 Implement athletics into running
  Scripts/CharacterWindow.gd
  Scripts/player.gd
Labels: enhancement

#215 Implement melee skill
  ItemProtosets.tres
  Mods/Core/Items/Items.json
  Mods/Core/Skills/Skills.json
  Scenes/ContentManager/Custom_Editors/ItemEditor/ItemMeleeEditor.tscn
  Scripts/EquippedItem.gd
  Scripts/ItemMeleeEditor.gd
  Scripts/gamedata.gd
Labels: enhancement

#217 Crafting menu respects volume in inventory
  ItemProtosets.tres
  Mods/Core/Items/Items.json
  Scenes/ContentManager/ModMaintenance/Scripts/changepropertytypescript.gd
  Scenes/ContentManager/ModMaintenance/changepropertytypescript.tscn
  Scenes/ContentManager/ModMaintenance/modmaintenance.tscn
  Scenes/ContentManager/Scripts/modmaintenance.gd
  Scenes/UI/CraftingMenu.tscn
  Scripts/CraftingMenu.gd
  Scripts/CtrlInventoryStackedCustom.gd
  Scripts/ItemEditor.gd
  Scripts/item_manager.gd
Labels: enhancement

#220 save load player skills
  Scripts/Helper/save_helper.gd
Labels: enhancement
