Repository Dimensionfall/Dimensionfall, pull requests merged in 2024-12, with the labels that each got.

#505 Allow basic modding for stats
  Scenes/ContentManager/ModMaintenance/Scripts/exportdata.gd
  Scenes/ContentManager/Scripts/content_list.gd
  Scenes/ContentManager/Scripts/contenteditor.gd
  Scripts/CharacterWindow.gd
  Scripts/Gamedata/DStats.gd
  Scripts/Runtimedata/RStat.gd
  Scripts/Runtimedata/RStats.gd
  Scripts/gamedata.gd
  Scripts/player.gd
  Scripts/runtimedata.gd
  Scripts/scene_selector.gd
  project.godot
Labels: enhancement

#494 (Wip) Monster factions 1.0
  ItemProtosets.tres
  Mods/Core/Mobfaction/Mobfactions.json
  Mods/Core/Mobgroups/Mobgroups.json
  Mods/Core/Mobs/Mobs.json
  Scenes/ContentManager/Custom_Editors/MobfactionsEditor.tscn
  Scenes/ContentManager/Custom_Editors/mobfactions_editor.gd
  Scenes/ContentManager/Scripts/contenteditor.gd
  Scenes/ContentManager/contenteditor.tscn
  Scripts/Gamedata/DMob.gd
  Scripts/Gamedata/DMobfaction.gd
  Scripts/Gamedata/DMobfactions.gd
  Scripts/gamedata.gd
Labels: enhancement

#509 Fix mob factions
  Media/Dimensionfall_mobgroup_editor.png.import
  Mods/Core/Mobfaction/Mobfactions.json
  Scenes/ContentManager/Custom_Editors/MobfactionsEditor.tscn
  Scenes/ContentManager/Scripts/contenteditor.gd
  Scripts/Gamedata/DMobfaction.gd
  Scripts/Gamedata/DMod.gd
  Scripts/gamedata.gd
Labels: bug

#507 Enable tacticalmap mods
  Scenes/ContentManager/Custom_Editors/TacticalMapEditor/Scripts/TacticalMapEditor.gd
  Scenes/ContentManager/Custom_Editors/TacticalMapEditor/Scripts/TileGrid.gd
  Scenes/ContentManager/Scripts/content_list.gd
  Scenes/ContentManager/Scripts/contenteditor.gd
  Scripts/Gamedata/DMap.gd
  Scripts/Gamedata/DMod.gd
  Scripts/Gamedata/DTacticalmaps.gd
  Scripts/OvermapGrid.gd
  Scripts/Runtimedata/RTacticalmap.gd
  Scripts/Runtimedata/RTacticalmaps.gd
  Scripts/gamedata.gd
  Scripts/runtimedata.gd
Labels: enhancement

#517 Allow maps to be modded
  Mods/Core/Maps/references.json
  Mods/Core/TacticalMaps/RockyHill_00.json
  Scenes/ContentManager/Custom_Editors/OvermapAreaEditor.tscn
  Scenes/ContentManager/Custom_Editors/Scripts/QuestEditor.gd
  Scenes/ContentManager/Custom_Editors/TacticalMapEditor/Scripts/EntitiesContainer.gd
  Scenes/ContentManager/Custom_Editors/TacticalMapEditor/Scripts/TacticalMapEditorTile.gd
  Scenes/ContentManager/Custom_Editors/TacticalMapEditor/Scripts/TileGrid.gd
  Scenes/ContentManager/Custom_Widgets/Scripts/overmap_area_region_editor.gd
  Scenes/ContentManager/Mapeditor/Scripts/GridContainer.gd
  Scenes/ContentManager/Scripts/content_list.gd
  Scenes/ContentManager/Scripts/contenteditor.gd
  Scripts/Chunk.gd
  Scripts/Gamedata/DFurniture.gd
  Scripts/Gamedata/DItemgroup.gd
  Scripts/Gamedata/DMap.gd
  Scripts/Gamedata/DMaps.gd
  Scripts/Gamedata/DMob.gd
  Scripts/Gamedata/DMobgroup.gd
  Scripts/Gamedata/DMod.gd
  Scripts/Gamedata/DMods.gd
  Scripts/Gamedata/DOvermaparea.gd
  Scripts/Gamedata/DQuest.gd
  Scripts/Gamedata/DTacticalmap.gd
  Scripts/Gamedata/DTacticalmaps.gd
  Scripts/Gamedata/DTile.gd
  Scripts/Helper/overmap_area_generator.gd
  Scripts/Helper/overmap_manager.gd
  Scripts/Helper/quest_helper.gd
  Scripts/OvermapGrid.gd
  Scripts/Runtimedata/RMap.gd
  Scripts/Runtimedata/RMaps.gd
  Scripts/Runtimedata/RTacticalmaps.gd
  Scripts/gamedata.gd
  Scripts/runtimedata.gd
Labels: enhancement

#520 Allow tiles to be modded
  Mods/Core/Tiles/Tiles.json
  Scenes/ContentManager/Custom_Editors/Scripts/TerrainTileEditor.gd
  Scenes/ContentManager/Mapeditor/Scripts/GridContainer.gd
  Scenes/ContentManager/Mapeditor/Scripts/TilebrushList.gd
  Scenes/ContentManager/Mapeditor/Scripts/mapeditor_brushcomposer.gd
  Scenes/ContentManager/Mapeditor/Scripts/mapeditortile.gd
  Scenes/ContentManager/Scripts/content_list.gd
  Scenes/ContentManager/Scripts/contenteditor.gd
  Scripts/Chunk.gd
  Scripts/Gamedata/DMap.gd
  Scripts/Gamedata/DMaps.gd
  Scripts/Gamedata/DMod.gd
  Scripts/Gamedata/DMods.gd
  Scripts/Gamedata/DTile.gd
  Scripts/Gamedata/DTiles.gd
  Scripts/Runtimedata/RTile.gd
  Scripts/Runtimedata/RTiles.gd
  Scripts/gamedata.gd
  Scripts/runtimedata.gd
Labels: enhancement

#522 Enable modding of overmaparea
  Scenes/ContentManager/Custom_Editors/Scripts/OvermapAreaEditor.gd
  Scenes/ContentManager/Custom_Widgets/Scripts/overmap_area_visualization.gd
  Scenes/ContentManager/Scripts/contenteditor.gd
  Scripts/Gamedata/DMod.gd
  Scripts/Gamedata/DOvermaparea.gd
  Scripts/Gamedata/DOvermapareas.gd
  Scripts/Gamedata/DTile.gd
  Scripts/Helper/overmap_area_generator.gd
  Scripts/OvermapGrid.gd
  Scripts/Runtimedata/RMap.gd
  Scripts/Runtimedata/ROvermaparea.gd
  Scripts/Runtimedata/ROvermapareas.gd
  Scripts/Runtimedata/RTile.gd
  Scripts/gamedata.gd
  Scripts/runtimedata.gd
Labels: enhancement

#527 Enable modding of skills
  Mods/Core/Skills/Skills.json
  Scenes/ContentManager/Custom_Editors/Scripts/SkillsEditor.gd
  Scenes/ContentManager/Scripts/content_list.gd
  Scenes/ContentManager/Scripts/contenteditor.gd
  Scenes/ContentManager/contenteditor.tscn
  Scripts/CharacterWindow.gd
  Scripts/Gamedata/DItem.gd
  Scripts/Gamedata/DMod.gd
  Scripts/Gamedata/DSkill.gd
  Scripts/Gamedata/DSkills.gd
  Scripts/Gamedata/DStats.gd
  Scripts/ItemCraftEditor.gd
  Scripts/ItemMeleeEditor.gd
  Scripts/ItemRangedEditor.gd
  Scripts/Runtimedata/RSkill.gd
  Scripts/Runtimedata/RSkills.gd
  Scripts/gamedata.gd
  Scripts/player.gd
  Scripts/runtimedata.gd
Labels: enhancement

#532 Allow quests to be modded
  Scenes/ContentManager/Custom_Editors/Scripts/QuestEditor.gd
  Scenes/ContentManager/Scripts/content_list.gd
  Scenes/ContentManager/Scripts/contenteditor.gd
  Scripts/Gamedata/DItem.gd
  Scripts/Gamedata/DMob.gd
  Scripts/Gamedata/DMobgroup.gd
  Scripts/Gamedata/DMod.gd
  Scripts/Gamedata/DQuest.gd
  Scripts/Gamedata/DQuests.gd
  Scripts/Helper/quest_helper.gd
  Scripts/QuestTrackerUI.gd
  Scripts/QuestWindow.gd
  Scripts/Runtimedata/RQuest.gd
  Scripts/Runtimedata/RQuests.gd
  Scripts/gamedata.gd
  Scripts/runtimedata.gd
Labels: enhancement

#534 Minor fixs and additions to editors
  Scenes/ContentManager/Custom_Editors/MobEditor.tscn
  Scenes/ContentManager/Custom_Editors/MobfactionsEditor.tscn
  Scenes/ContentManager/Custom_Editors/QuestEditor.tscn
  Scenes/ContentManager/Custom_Widgets/DropEnabledTextEdit.tscn
  Scripts/Gamedata/DMobfaction.gd
Labels: enhancement

#535 Now the relation type is displayed in label_instance (MobFactionEditor)
  Mods/Core/Mobfaction/Mobfactions.json
  Mods/Core/Mobgroups/Mobgroups.json
  Mods/Core/Mobs/Mobs.json
  Scenes/ContentManager/Custom_Editors/mobfactions_editor.gd
  Scripts/Gamedata/DMobfaction.gd
Labels: enhancement

#536 Some minor fixes and additions
  Media/Dimensionfall_mobfaction_editor.png
  Media/Dimensionfall_mobfaction_editor.png.import
  README.md
  Scenes/ContentManager/Custom_Editors/MobfactionsEditor.tscn
Labels: documentation, enhancement

#538 Enable modding of playerattributes
  Mods/Core/PlayerAttributes/PlayerAttributes.json
  Mods/Core/PlayerAttributes/references.json
  Scenes/ContentManager/Custom_Editors/Scripts/MobEditor.gd
  Scenes/ContentManager/Custom_Editors/Scripts/PlayerAttributeEditor.gd
  Scenes/ContentManager/Scripts/content_list.gd
  Scenes/ContentManager/Scripts/contenteditor.gd
  Scripts/Gamedata/DItem.gd
  Scripts/Gamedata/DMob.gd
  Scripts/Gamedata/DMod.gd
  Scripts/Gamedata/DPlayerAttribute.gd
  Scripts/Gamedata/DPlayerAttributes.gd
  Scripts/Gamedata/DSkills.gd
  Scripts/InventoryWindow.gd
  Scripts/ItemFoodEditor.gd
  Scripts/ItemMedicalEditor.gd
  Scripts/ItemWearableEditor.gd
  Scripts/PlayerAttribute.gd
  Scripts/Runtimedata/RPlayerAttribute.gd
  Scripts/Runtimedata/RPlayerAttributes.gd
  Scripts/gamedata.gd
  Scripts/player.gd
  Scripts/runtimedata.gd
Labels: enhancement

#537 Fix dragging from content list
  Scenes/ContentManager/Scripts/content_list.gd
Labels: bug

#540 move wearableslots to mods
  ItemProtosets.tres
  Mods/Core/Items/Items.json
  Mods/Core/Wearableslots/Wearableslots.json
  Mods/Core/Wearableslots/references.json
  Scenes/ContentManager/Custom_Editors/ItemEditor/ItemWearableEditor.tscn
  Scenes/ContentManager/Custom_Editors/Scripts/WearableslotEditor.gd
  Scenes/ContentManager/Scripts/content_list.gd
  Scenes/ContentManager/Scripts/contenteditor.gd
  Scripts/Gamedata/DItem.gd
  Scripts/Gamedata/DMod.gd
  Scripts/Gamedata/DMods.gd
  Scripts/Gamedata/DWearableSlot.gd
  Scripts/Gamedata/DWearableSlots.gd
  Scripts/InventoryWindow.gd
  Scripts/ItemWearableEditor.gd
  Scripts/Runtimedata/RWearableSlot.gd
  Scripts/Runtimedata/RWearableSlots.gd
  Scripts/WearableSlot.gd
  Scripts/gamedata.gd
  Scripts/runtimedata.gd
Labels: enhancement

#543 Fixed an issue where the game doesn't stop tracking time in pause menu.
  Scripts/EscapeMenu.gd
Labels: bug

#546 Updated main menu tips
  scene_selector.tscn
Labels: documentation

#545 Fixed an issue where the tooltip stayed open when you double clicked on the last item in a container.
  Scripts/InventoryWindow.gd
Labels: bug

#548 Allow mobs to be modded
  Scenes/ContentManager/Custom_Editors/Scripts/MobEditor.gd
  Scenes/ContentManager/Custom_Editors/Scripts/MobgroupsEditor.gd
  Scenes/ContentManager/Custom_Editors/Scripts/QuestEditor.gd
  Scenes/ContentManager/Custom_Editors/mobfactions_editor.gd
  Scenes/ContentManager/Mapeditor/Scripts/TilebrushList.gd
  Scenes/ContentManager/Mapeditor/Scripts/mapeditor_brushcomposer.gd
  Scenes/ContentManager/Mapeditor/Scripts/mapeditortile.gd
  Scenes/ContentManager/Scripts/contenteditor.gd
  Scripts/Gamedata/DMap.gd
  Scripts/Gamedata/DMob.gd
  Scripts/Gamedata/DMobfaction.gd
  Scripts/Gamedata/DMobgroup.gd
  Scripts/Gamedata/DMobs.gd
  Scripts/Gamedata/DMod.gd
  Scripts/Gamedata/DQuest.gd
  Scripts/Helper/quest_helper.gd
  Scripts/Mob/Mob.gd
  Scripts/QuestTrackerUI.gd
  Scripts/QuestWindow.gd
  Scripts/Runtimedata/RMob.gd
  Scripts/Runtimedata/RMobs.gd
  Scripts/gamedata.gd
  Scripts/runtimedata.gd
Labels: enhancement

#549 prevent Loading screen from disappearing when returning to main menu
  Scripts/EscapeMenu.gd
  hud.tscn
  level_generation.tscn
Labels: bug

#553 Allow mobgroups to be modded
  Mods/Core/Maps/Generichouse.json
  Mods/Core/Maps/Generichouse_00.json
  Mods/Core/Maps/RockyHill_NE.json
  Mods/Core/Maps/RockyHill_NW.json
  Mods/Core/Maps/RockyHill_SE.json
  Mods/Core/Maps/RockyHill_SW.json
  Mods/Core/Maps/abandoned_building.json
  Mods/Core/Maps/city_square.json
  Mods/Core/Maps/field_grass_basic_00.json
  Mods/Core/Maps/field_grass_flowers_00.json
  Mods/Core/Maps/field_grass_hill_00.json
  Mods/Core/Maps/field_grass_hole_00.json
  Mods/Core/Maps/forest_basic_00.json
  Mods/Core/Maps/generichouse_corner.json
  Mods/Core/Maps/generichouse_cross.json
  Mods/Core/Maps/generichouse_end.json
  Mods/Core/Maps/generichouse_t.json
  Mods/Core/Maps/neighborhood_school.json
  Mods/Core/Maps/office_building_00.json
  Mods/Core/Maps/parking_garage.json
  Mods/Core/Maps/police_station.json
  Mods/Core/Maps/radio_tower.json
  Mods/Core/Maps/skyscraper.json
  Mods/Core/Maps/store_electronic_clothing.json
  Mods/Core/Maps/store_groceries.json
  Mods/Core/Maps/subway_station.json
  Mods/Core/Maps/two_story_house.json
  Mods/Core/Mobgroups/references.json
  Mods/Core/Mobs/Mobs.json
  Mods/Core/Mobs/references.json
  Mods/Core/Tiles/references.json
  Scenes/ContentManager/Custom_Editors/Scripts/MobgroupsEditor.gd
  Scenes/ContentManager/Custom_Editors/Scripts/QuestEditor.gd
  Scenes/ContentManager/Custom_Editors/mobfactions_editor.gd
  Scenes/ContentManager/Mapeditor/Scripts/TilebrushList.gd
  Scenes/ContentManager/Mapeditor/Scripts/mapeditor_brushcomposer.gd
  Scenes/ContentManager/Mapeditor/Scripts/mapeditortile.gd
  Scenes/ContentManager/Scripts/content_list.gd
  Scenes/ContentManager/Scripts/contenteditor.gd
  Scripts/Chunk.gd
  Scripts/Gamedata/DMap.gd
  Scripts/Gamedata/DMob.gd
  Scripts/Gamedata/DMobfaction.gd
  Scripts/Gamedata/DMobgroup.gd
  Scripts/Gamedata/DMobgroups.gd
  Scripts/Gamedata/DMobs.gd
  Scripts/Gamedata/DMod.gd
  Scripts/Gamedata/DOvermapareas.gd
  Scripts/Gamedata/DQuest.gd
  Scripts/Helper/quest_helper.gd
  Scripts/QuestTrackerUI.gd
  Scripts/QuestWindow.gd
  Scripts/Runtimedata/RMobgroup.gd
  Scripts/Runtimedata/RMobgroups.gd
  Scripts/gamedata.gd
  Scripts/runtimedata.gd
Labels: enhancement

#555 Create runtimedata in test environment
  Scenes/ContentManager/Mapeditor/Scripts/GridContainer.gd
Labels: bug

#556 Fixed an issue where shooting sound didn't play when shot from left hand
  level_generation.tscn
Labels: bug

#558 Fixed an issue where reload sound doesn't play after reloading the gun for the second time without unequipping
  Scripts/EquippedItem.gd
  Scripts/PlayerShooting.gd
Labels: bug

#559 Fixed an issue where reload sound doesn't play when you reload the pistol from sub menu
  Scenes/UI/CtrlInventoryStackedCustom.tscn
  Scripts/CtrlInventoryStackedCustom.gd
Labels: bug

#560 Load sprites from the mod
  Scenes/ContentManager/Custom_Editors/Scripts/TerrainTileEditor.gd
  Scripts/Gamedata/DTiles.gd
Labels: bug

#561 Enable modding of itemgroups
  Scenes/ContentManager/Custom_Editors/Scripts/FurnitureEditor.gd
  Scenes/ContentManager/Custom_Editors/Scripts/ItemgroupEditor.gd
  Scenes/ContentManager/Custom_Editors/Scripts/MobEditor.gd
  Scenes/ContentManager/Custom_Widgets/Scripts/Editable_Item_List.gd
  Scenes/ContentManager/Mapeditor/Scripts/mapeditor_brushcomposer.gd
  Scenes/ContentManager/Mapeditor/Scripts/mapeditortile.gd
  Scenes/ContentManager/Scripts/content_list.gd
  Scenes/ContentManager/Scripts/contenteditor.gd
  Scripts/FurniturePhysicsSrv.gd
  Scripts/FurnitureStaticSrv.gd
  Scripts/Gamedata/DFurniture.gd
  Scripts/Gamedata/DItem.gd
  Scripts/Gamedata/DItemgroup.gd
  Scripts/Gamedata/DItemgroups.gd
  Scripts/Gamedata/DMap.gd
  Scripts/Gamedata/DMob.gd
  Scripts/Gamedata/DMobs.gd
  Scripts/Gamedata/DMod.gd
  Scripts/Runtimedata/RItemgroup.gd
  Scripts/Runtimedata/RItemgroups.gd
  Scripts/container.gd
  Scripts/gamedata.gd
  Scripts/general.gd
  Scripts/runtimedata.gd
Labels: enhancement

#564 Move mobfactions to mods
  Scenes/ContentManager/Custom_Editors/mobfactions_editor.gd
  Scenes/ContentManager/Scripts/content_list.gd
  Scenes/ContentManager/Scripts/contenteditor.gd
  Scripts/Gamedata/DMobfaction.gd
  Scripts/Gamedata/DMobfactions.gd
  Scripts/Gamedata/DMod.gd
  Scripts/OvermapGrid.gd
  Scripts/Runtimedata/RMobfaction.gd
  Scripts/Runtimedata/RMobfactions.gd
  Scripts/gamedata.gd
  Scripts/runtimedata.gd
Labels: enhancement

#567 Regenerate containers
  Mods/Core/Furniture/Furniture.json
  Mods/Core/Itemgroups/Itemgroups.json
  Mods/Core/Itemgroups/references.json
  Mods/Core/Items/references.json
  Scenes/ContentManager/Custom_Editors/FurnitureEditor.tscn
  Scenes/ContentManager/Custom_Editors/Scripts/FurnitureEditor.gd
  Scripts/FurnitureStaticSpawner.gd
  Scripts/FurnitureStaticSrv.gd
  Scripts/Gamedata/DFurniture.gd
  Scripts/Helper/time_helper.gd
  Scripts/Runtimedata/RFurniture.gd
  Scripts/Runtimedata/RItemgroup.gd
  Scripts/Runtimedata/RMobfaction.gd
  Scripts/Runtimedata/RMobgroup.gd
Labels: enhancement

#570 Mod load order
  Scenes/ContentManager/Scripts/addremovemods.gd
  Scenes/ContentManager/addremovemods.tscn
  Scripts/Gamedata/DMod.gd
  Scripts/Gamedata/DMods.gd
  Scripts/Runtimedata/RFurnitures.gd
  Scripts/Runtimedata/RItemgroups.gd
  Scripts/Runtimedata/RItems.gd
  Scripts/Runtimedata/RMaps.gd
  Scripts/Runtimedata/RMobfactions.gd
  Scripts/Runtimedata/RMobgroups.gd
  Scripts/Runtimedata/RMobs.gd
  Scripts/Runtimedata/ROvermapareas.gd
  Scripts/Runtimedata/RPlayerAttributes.gd
  Scripts/Runtimedata/RQuests.gd
  Scripts/Runtimedata/RSkills.gd
  Scripts/Runtimedata/RStats.gd
  Scripts/Runtimedata/RTacticalmaps.gd
  Scripts/Runtimedata/RTiles.gd
  Scripts/Runtimedata/RWearableSlots.gd
  Scripts/runtimedata.gd
Labels: enhancement

#574 Update game architecture and readme
  Documentation/Game_design/Game_architecture.md
  README.md
Labels: documentation

#575 Move playerattributes to Dimensionfall mod
  Mods/Core/Maps/default_map.json
  Mods/Core/PlayerAttributes/PlayerAttributes.json
  Mods/Core/PlayerAttributes/references.json
  Mods/Core/Tiles/DefaultTile.png
  Mods/Core/Tiles/Tiles.json
  Mods/Core/Tiles/references.json
  Mods/Dimensionfall/PlayerAttributes/PlayerAttributes.json
  Mods/Dimensionfall/PlayerAttributes/apple_32.png
  Mods/Dimensionfall/PlayerAttributes/apple_32.png.import
  Mods/Dimensionfall/PlayerAttributes/head_32.png
  Mods/Dimensionfall/PlayerAttributes/head_32.png.import
  Mods/Dimensionfall/PlayerAttributes/left_arm_32.png
  Mods/Dimensionfall/PlayerAttributes/left_arm_32.png.import
  Mods/Dimensionfall/PlayerAttributes/left_leg_32.png
  Mods/Dimensionfall/PlayerAttributes/left_leg_32.png.import
  Mods/Dimensionfall/PlayerAttributes/references.json
  Mods/Dimensionfall/PlayerAttributes/right_arm_32.png
  Mods/Dimensionfall/PlayerAttributes/right_arm_32.png.import
  Mods/Dimensionfall/PlayerAttributes/right_leg_32.png
  Mods/Dimensionfall/PlayerAttributes/right_leg_32.png.import
  Mods/Dimensionfall/PlayerAttributes/skull_poison_32.png
  Mods/Dimensionfall/PlayerAttributes/skull_poison_32.png.import
  Mods/Dimensionfall/PlayerAttributes/torso_32.png
  Mods/Dimensionfall/PlayerAttributes/torso_32.png.import
  Mods/Dimensionfall/PlayerAttributes/trapping_32.png
  Mods/Dimensionfall/PlayerAttributes/trapping_32.png.import
  Mods/Dimensionfall/PlayerAttributes/waterbottle_32.png
  Mods/Dimensionfall/PlayerAttributes/waterbottle_32.png.import
Labels: enhancement

#576 Remember the selected mod in content editor and map editor
  Scenes/ContentManager/Mapeditor/Scripts/TilebrushList.gd
  Scenes/ContentManager/Mapeditor/mapeditor.tscn
  Scenes/ContentManager/Scripts/contenteditor.gd
Labels: enhancement

#577 Add bud's sprites and items
  ItemProtosets.tres
  Mods/Dimensionfall/Itemgroups/Itemgroups.json
  Mods/Dimensionfall/Items/Items.json
  Mods/Dimensionfall/Items/apple_32.png
  Mods/Dimensionfall/Items/cirquit_board_32.png
  Mods/Dimensionfall/Items/kiwi_32.png
  Mods/Dimensionfall/Items/kiwi_32.png.import
  Mods/Dimensionfall/Items/references.json
  Mods/Dimensionfall/Items/uncooked_meat_32.png
  Mods/Dimensionfall/Items/uncooked_meat_32.png.import
Labels: enhancement

#578 Increase sprite size to 64 in sprite selector
  Scenes/ContentManager/Custom_Widgets/Scripts/Selectable_Sprite_Widget.gd
  Scenes/ContentManager/Custom_Widgets/Selectable_Sprite_Widget.tscn
Labels: enhancement

#579 Various item references fixes
  Mods/Core/PlayerAttributes/references.json
  Mods/Dimensionfall/Items/Items.json
  Mods/Dimensionfall/Items/references.json
  Mods/Dimensionfall/Maps/references.json
  Mods/Dimensionfall/Mobgroups/references.json
  Mods/Dimensionfall/Mobs/references.json
  Mods/Dimensionfall/PlayerAttributes/references.json
  Mods/Dimensionfall/Skills/references.json
  Scripts/Gamedata/DItem.gd
  Scripts/Gamedata/DItems.gd
  Scripts/ItemEditor.gd
  Scripts/ItemMedicalEditor.gd
Labels: bug

#584 Fix reference viewer
  Scenes/ContentManager/Custom_Editors/Scripts/ReferencesEditor.gd
  Scripts/Gamedata/DItems.gd
  Scripts/ItemEditor.gd
Labels: bug

#585 Add crafting data to furniture
  Mods/Dimensionfall/Furniture/Furniture.json
  Mods/Dimensionfall/Items/references.json
  Scenes/ContentManager/Custom_Editors/FurnitureEditor.tscn
  Scenes/ContentManager/Custom_Editors/Scripts/FurnitureEditor.gd
  Scripts/Gamedata/DFurniture.gd
  Scripts/Gamedata/DFurnitures.gd
  Scripts/Gamedata/DItem.gd
  Scripts/Gamedata/DItems.gd
  Scripts/Runtimedata/RFurniture.gd
Labels: enhancement

#588 Craftingcontainer
  Scenes/ContentManager/Custom_Editors/ItemEditor/ItemCraftEditor.tscn
  Scripts/FurnitureStaticSrv.gd
  Scripts/Helper/time_helper.gd
  Scripts/Runtimedata/RFurniture.gd
  Scripts/Runtimedata/RItem.gd
  Scripts/Runtimedata/RItems.gd
Labels: enhancement

#589 Add interface for crafting stations
  Scenes/UI/FurnitureWindow.tscn
  Scripts/CtrlInventoryStackedCustom.gd
  Scripts/Door.gd
  Scripts/EscapeMenu.gd
  Scripts/FurnitureStaticSpawner.gd
  Scripts/FurnitureStaticSrv.gd
  Scripts/FurnitureWindow.gd
  Scripts/Helper/signal_broker.gd
  Scripts/Runtimedata/RFurniture.gd
  Scripts/player.gd
  hud.tscn
Labels: enhancement

#590 Furniture crafting UI
  Scenes/UI/FurnitureWindow.tscn
  Scripts/BuildManager.gd
  Scripts/CraftingMenu.gd
  Scripts/FurnitureStaticSrv.gd
  Scripts/FurnitureWindow.gd
  Scripts/item_manager.gd
Labels: enhancement

#592 Wearableslots
  Mods/Dimensionfall/Itemgroups/Itemgroups.json
  Mods/Dimensionfall/Items/references.json
  Mods/Dimensionfall/Wearableslots/Wearableslots.json
  Scenes/ContentManager/Custom_Editors/Scripts/WearableslotEditor.gd
  Scenes/ContentManager/Custom_Editors/WearableslotEditor.tscn
  Scripts/CtrlInventoryStackedCustom.gd
  Scripts/Gamedata/DItem.gd
  Scripts/Gamedata/DWearableSlot.gd
  Scripts/Gamedata/DWearableSlots.gd
  Scripts/Runtimedata/RWearableSlot.gd
  Scripts/item_manager.gd
Labels: enhancement

#593 Forest camp map, campfire
  Mods/Dimensionfall/Furniture/Furniture.json
  Mods/Dimensionfall/Furniture/campfire_off_64.png
  Mods/Dimensionfall/Furniture/campfire_off_64.png.import
  Mods/Dimensionfall/Furniture/campfire_on_64.png
  Mods/Dimensionfall/Furniture/campfire_on_64.png.import
  Mods/Dimensionfall/Furniture/references.json
  Mods/Dimensionfall/Itemgroups/references.json
  Mods/Dimensionfall/Maps/forest_camp_00.json
  Mods/Dimensionfall/Maps/forest_camp_00.png
  Mods/Dimensionfall/Maps/forest_camp_00.png.import
  Mods/Dimensionfall/Maps/references.json
  Mods/Dimensionfall/TacticalMaps/forest_custom.json
  Mods/Dimensionfall/Tiles/references.json
  Scenes/ContentManager/Custom_Editors/TacticalMapEditor/Scripts/EntitiesContainer.gd
  Scenes/ContentManager/Mapeditor/Scripts/mapeditor_brushcomposer.gd
Labels: enhancement

#595 Allow tacticalmapeditor to select mods
  Scenes/ContentManager/Custom_Editors/TacticalMapEditor/Scripts/EntitiesContainer.gd
  Scenes/ContentManager/Custom_Editors/TacticalMapEditor/TacticalMapEditor.tscn
Labels: bug

#596 Add furniture construction recipe
  Mods/Dimensionfall/Furniture/Furniture.json
  Mods/Dimensionfall/Items/references.json
  Scenes/ContentManager/Custom_Editors/FurnitureEditor.tscn
  Scenes/ContentManager/Custom_Editors/Scripts/FurnitureEditor.gd
  Scripts/Gamedata/DFurniture.gd
  Scripts/Gamedata/DFurnitures.gd
  Scripts/Runtimedata/RFurniture.gd
Labels: enhancement
