Repository Dimensionfall/Dimensionfall, pull requests merged in 2025-01, with the labels that each got.

#599 Allow placing furniture trough the building menu
  Defaults/Blocks/Materials/construction_ghost_material.tres
  Scenes/UI/BuildingMenu.tscn
  Scripts/BuildManager.gd
  Scripts/BuildingMenu.gd
  Scripts/Chunk.gd
  Scripts/ConstructionGhost.gd
  Scripts/EscapeMenu.gd
  Scripts/FurnitureStaticSpawner.gd
  Scripts/Helper/signal_broker.gd
  Scripts/Runtimedata/RFurniture.gd
  Scripts/Runtimedata/RFurnitures.gd
  Scripts/hud.gd
  hud.tscn
  level_generation.tscn
Labels: enhancement

#611 Update crafting ui when re-opened
  Scripts/ConstructionGhost.gd
  Scripts/CraftingMenu.gd
Labels: bug

#614 Equipped items count for quest
  Scripts/EquipmentSlot.gd
  Scripts/Helper/quest_helper.gd
Labels: bug

#628 Save game at start
  Scripts/Helper/save_helper.gd
  Scripts/LoadingScreen.gd
Labels: enhancement

#630 Destroy furniture that's not a container without crash
  Scripts/FurnitureStaticSrv.gd
Labels: bug

#637 Add input manager class and use key/value signals to drive held item updates
  Scenes/InventoryWindow.tscn
  Scenes/input_manager.tscn
  Scenes/player.tscn
  Scripts/EquipmentSlot.gd
  Scripts/EquippedItem.gd
  Scripts/Helper.gd
  Scripts/Helper/SignalBroker/player_input_signal_broker.gd
  Scripts/Helper/SignalBroker/signal_broker.gd
  Scripts/Helper/SignalBroker/signal_factory.gd
  Scripts/input_manager.gd
  Scripts/item_manager.gd
  Scripts/player.gd
  level_generation.tscn
Labels: enhancement

#634 Split readme into featurelist
  FeatureList.md
  Media/Dimensionfall_crafting_station.png
  Media/Dimensionfall_crafting_station.png.import
  Mods/Dimensionfall/Itemgroups/Itemgroups.json
  Mods/Dimensionfall/Items/references.json
  README.md
Labels: documentation

#635 Sort the saved games list in main menu
  Scripts/scene_selector.gd
Labels: enhancement

#638 Dev/remove hand specific fields
  Scripts/EquippedItem.gd
  Scripts/Helper/SignalBroker/signal_broker.gd
  Scripts/hud.gd
  Scripts/input_manager.gd
  hud.tscn
Labels: enhancement

#639 Mobs from different factions attack eachother
  Scripts/Mob/Detection.gd
  Scripts/Mob/Mob.gd
  Scripts/Mob/MobAttack.gd
  Scripts/Mob/MobFollow.gd
  Scripts/Mob/MobIdle.gd
  Scripts/Mob/MobTerminate.gd
  Scripts/Runtimedata/RMobfaction.gd
  Scripts/player.gd
Labels: enhancement

#644 Furniture can consume items, enabling the concept of fuel or power
  Mods/Dimensionfall/Furniture/Furniture.json
  Scenes/ContentManager/Custom_Editors/FurnitureEditor.tscn
  Scenes/ContentManager/Custom_Editors/Scripts/FurnitureEditor.gd
  Scenes/UI/FurnitureWindow.tscn
  Scripts/FurnitureStaticSpawner.gd
  Scripts/FurnitureStaticSrv.gd
  Scripts/FurnitureWindow.gd
  Scripts/Gamedata/DFurniture.gd
  Scripts/Gamedata/DFurnitures.gd
  Scripts/Runtimedata/RFurniture.gd
Labels: enhancement

#649 Industrial zone furniture and maps
  ItemProtosets.tres
  Mods/Dimensionfall/Furniture/Furniture.json
  Mods/Dimensionfall/Furniture/car_00_300_200.png
  Mods/Dimensionfall/Furniture/car_00_300_200.png.import
  Mods/Dimensionfall/Furniture/car_01_300_200.png
  Mods/Dimensionfall/Furniture/car_01_300_200.png.import
  Mods/Dimensionfall/Furniture/conveyor_corner_100.png
  Mods/Dimensionfall/Furniture/conveyor_corner_100.png.import
  Mods/Dimensionfall/Furniture/conveyor_straight_100.png
  Mods/Dimensionfall/Furniture/conveyor_straight_100.png.import
  Mods/Dimensionfall/Furniture/machine_conveyor_end_100.png
  Mods/Dimensionfall/Furniture/machine_conveyor_end_100.png.import
  Mods/Dimensionfall/Furniture/machine_conveyor_mid_100.png
  Mods/Dimensionfall/Furniture/machine_conveyor_mid_100.png.import
  Mods/Dimensionfall/Furniture/machine_light_standalone_64.png
  Mods/Dimensionfall/Furniture/machine_light_standalone_64.png.import
  Mods/Dimensionfall/Furniture/references.json
  Mods/Dimensionfall/Furniture/tanker_250_400.png
  Mods/Dimensionfall/Furniture/tanker_250_400.png.import
  Mods/Dimensionfall/Furniture/truck_00_600_250.png
  Mods/Dimensionfall/Furniture/truck_00_600_250.png.import
  Mods/Dimensionfall/Furniture/wooden_crate_48_64.png
  Mods/Dimensionfall/Furniture/wooden_crate_48_64.png.import
  Mods/Dimensionfall/Furniture/wooden_crate_64.png
  Mods/Dimensionfall/Furniture/wooden_crate_64.png.import
  Mods/Dimensionfall/Itemgroups/references.json
  Mods/Dimensionfall/Maps/factory_hall.json
  Mods/Dimensionfall/Maps/factory_hall.png
  Mods/Dimensionfall/Maps/factory_hall.png.import
  Mods/Dimensionfall/Maps/industrial_control_center.json
  Mods/Dimensionfall/Maps/industrial_control_center.png
  Mods/Dimensionfall/Maps/industrial_control_center.png.import
  Mods/Dimensionfall/Maps/references.json
  Mods/Dimensionfall/Maps/scrap_yard.json
  Mods/Dimensionfall/Maps/scrap_yard.png
  Mods/Dimensionfall/Maps/scrap_yard.png.import
  Mods/Dimensionfall/Maps/warehouse_storage.json
  Mods/Dimensionfall/Maps/warehouse_storage.png
  Mods/Dimensionfall/Maps/warehouse_storage.png.import
  Mods/Dimensionfall/Mobgroups/references.json
  Mods/Dimensionfall/TacticalMaps/industrial_zone.json
  Mods/Dimensionfall/Tiles/references.json
  Scenes/ContentManager/Custom_Editors/Scripts/OvermapAreaEditor.gd
  Scenes/ContentManager/Custom_Widgets/Scripts/Selectable_Sprite_Widget.gd
  Scenes/ContentManager/Custom_Widgets/Scripts/overmap_area_visualization.gd
  Scripts/FurnitureStaticSrv.gd
  Scripts/Helper/overmap_area_generator.gd
  Scripts/OvermapGrid.gd
Labels: enhancement

#650 Fix overmaparea, fix cigarettes, fix furniture shape sprite
  ItemProtosets.tres
  Mods/Dimensionfall/Itemgroups/Itemgroups.json
  Mods/Dimensionfall/Items/Items.json
  Mods/Dimensionfall/Items/references.json
  Scenes/ContentManager/Custom_Editors/FurnitureEditor.tscn
  Scenes/ContentManager/Custom_Editors/Scripts/FurnitureEditor.gd
  Scripts/Gamedata/DItem.gd
  Scripts/Gamedata/DItemgroups.gd
  Scripts/Gamedata/DMods.gd
  Scripts/Gamedata/DOvermaparea.gd
  Scripts/Gamedata/DWearableSlot.gd
Labels: bug

#652 Overmapgrid no longer overwrites tacticalmaps with roads
  ItemProtosets.tres
  Scripts/OvermapGrid.gd
Labels: bug

#653 Melee attack no longer hits trough walls
  Scripts/EquippedItem.gd
  Scripts/Gamedata/DItems.gd
Labels: bug
