Repository Dimensionfall/Dimensionfall, pull requests merged in 2025-05, with the labels that each got.

#726 Added several pieces of music to the gameplay
  ItemProtosets.tres
  README.md
  Scripts/EscapeMenu.gd
  Scripts/player.gd
  Scripts/scene_selector.gd
  Sounds/Music/Music.gd
  Sounds/Music/Music.tscn
  Sounds/Music/Please, answer me my friend.mp3
  Sounds/Music/Please, answer me my friend.mp3.import
  Sounds/Music/Pressure.ogg
  Sounds/Music/Pressure.ogg.import
  Sounds/Music/The Depths of Hell.mp3
  Sounds/Music/The Depths of Hell.mp3.import
  Sounds/Music/The Surreal Truth.mp3
  Sounds/Music/The Surreal Truth.mp3.import
  Sounds/Music/dark fallout.ogg
  Sounds/Music/dark fallout.ogg.import
Labels: enhancement

#728 Moved most of the sound related code to HELPER.gd + added ambient sounds
  README.md
  Scripts/EscapeMenu.gd
  Scripts/GameOver.gd
  Scripts/Helper.gd
  Scripts/player.gd
  Scripts/scene_selector.gd
  Sounds/Ambience/Ambience.tscn
  Sounds/Ambience/AmbientNatureBirdsWater01.wav
  Sounds/Ambience/AmbientNatureBirdsWater01.wav.import
  Sounds/Ambience/AmbientNatureNightRainy.wav
  Sounds/Ambience/AmbientNatureNightRainy.wav.import
  Sounds/Ambience/AmbientNatureOutside.wav
  Sounds/Ambience/AmbientNatureOutside.wav.import
  Sounds/Ambience/ambience.gd
  Sounds/Ambience/ambience.gd.uid
  Sounds/Ambience/cricketsounds.mp3
  Sounds/Ambience/cricketsounds.mp3.import
  Sounds/Music/Music.gd
  Sounds/Music/Music.tscn
  Sounds/SFX/sfx.gd
  Sounds/SFX/sfx.gd.uid
  Sounds/SFX/sfx.tscn
  Sounds/default_bus_layout.tres
  project.godot
Labels: enhancement

#730 Added hurt sounds to the game + a minor code overhaul.
  Images/Main menu/Dimensionfall.jpg
  Images/Main menu/Dimensionfall.jpg.import
  ItemProtosets.tres
  README.md
  Scenes/LoadingScreen.tscn
  Scripts/Helper.gd
  Scripts/player.gd
  Sounds/Ambience/ambience.gd
  Sounds/Ambience/wind1.wav.import
  Sounds/Music/Music.tscn
  Sounds/SFX/Hurt sounds (Male)/aargh0.ogg
  Sounds/SFX/Hurt sounds (Male)/aargh0.ogg.import
  Sounds/SFX/Hurt sounds (Male)/aargh2.ogg
  Sounds/SFX/Hurt sounds (Male)/aargh2.ogg.import
  Sounds/SFX/Hurt sounds (Male)/aargh4.ogg
  Sounds/SFX/Hurt sounds (Male)/aargh4.ogg.import
  Sounds/SFX/Hurt sounds (Male)/aargh6.ogg
  Sounds/SFX/Hurt sounds (Male)/aargh6.ogg.import
  Sounds/SFX/sfx.gd
  scene_selector.tscn
  thumb-1920-83970.jpg
  thumb-1920-83970.jpg.import
Labels: enhancement

#729 Implement new ui for in-game windows
  FeatureList.md
  Media/Catax_inventory.png
  Media/Catax_main_menu.png
  Media/Catax_overmap.png
  Media/Catax_quest_journal.png
  Media/Dimensionfall_crafting_station.png
  Media/Dimensionfall_inventory.png
  Media/Dimensionfall_inventory.png.import
  Media/Dimensionfall_main_menu.png
  Media/Dimensionfall_main_menu.png.import
  Media/Dimensionfall_overmap.png
  Media/Dimensionfall_overmap.png.import
  Media/Dimensionfall_quest_journal.png
  Media/Dimensionfall_quest_journal.png.import
  Scenes/InventoryWindow.tscn
  Scenes/Overmap/Overmap.tscn
  Scenes/Overmap/Scripts/Overmap.gd
  Scenes/UI/CharacterWindow.tscn
  Scenes/UI/FurnitureConstructionWindow.tscn
  Scenes/UI/FurnitureWindow.tscn
  Scenes/UI/QuestWindow.tscn
  Scenes/UI/StyleBoxFlat_WindowBody.tres
  Scenes/UI/StyleBoxFlat_WindowHeader.tres
  Scenes/UI/main_window_contianer.tscn
  Scripts/CharacterWindow.gd
  Scripts/InventoryWindow.gd
  Scripts/QuestWindow.gd
  hud.tscn
Labels: enhancement

#732 Updated FeatureList.md
  FeatureList.md
Labels: bug

#733 Update the main menu picture
  Media/Dimensionfall_main_menu.png
Labels: documentation

#735 Fix melee attack range
  Scenes/player.tscn
  Tests/Unit/test_player.gd
  level_generation.tscn
Labels: bug

#736 Added more background pictures to several menus and fixed the anchors
  Images/Main menu/AI_Options_background.jpg
  Images/Main menu/AI_Options_background.jpg.import
  Images/Main menu/AI_Title.jpg
  Images/Main menu/AI_Title.jpg.import
  Images/Main menu/AI_bloody_background.jpg
  Images/Main menu/AI_bloody_background.jpg.import
  ItemProtosets.tres
  Scenes/ContentManager/contentmanager.tscn
  Scenes/ContentManager/modmanager.tscn
  Scenes/ContentManager/othertools.tscn
  Scenes/GameOver.tscn
  Scenes/LoadingScreen.tscn
  Scenes/UI/EscapeMenu.tscn
  Scenes/player.tscn
  scene_selector.tscn
Labels: enhancement

#743 Walking sounds in progress + cool effect on loading screen
  ItemProtosets.tres
  Scenes/LoadingScreen.tscn
  Scenes/UI/EscapeMenu.tscn
  Scenes/player.tscn
  Scripts/LoadingScreen.gd
  Scripts/player.gd
  Scripts/scene_selector.gd
  Sounds/Music/Music.gd
  Sounds/SFX/sfx.gd
  Sounds/SFX/sfx.tscn
Labels: enhancement

#750 New main menu screen
  Apple ][.ttf
  Apple ][.ttf.import
  Glitch.ttf
  Glitch.ttf.import
  Images/Main menu/AI_title_background.jpg
  Images/Main menu/AI_title_background.jpg.import
  ItemProtosets.tres
  Main_menu_buttons.tres
  README.md
  Scripts/scene_selector.gd
  Sounds/Music/Music.gd
  Sounds/Music/Music.tscn
  Sounds/SFX/UI/MouseClick.mp3
  Sounds/SFX/UI/MouseClick.mp3.import
  Sounds/SFX/UI/computer-humming-236384.mp3
  Sounds/SFX/UI/computer-humming-236384.mp3.import
  Sounds/SFX/UI/mech-keyboard-02-102918.mp3
  Sounds/SFX/UI/mech-keyboard-02-102918.mp3.import
  Sounds/SFX/sfx.gd
  button_gui.tres
  scene_selector.tscn
Labels: enhancement

#752 Major main menu overhaul
  Images/Main menu/AI_Options_background.jpg
  Images/Main menu/AI_Options_background.jpg.import
  Images/Main menu/AI_Title.jpg
  Images/Main menu/AI_Title.jpg.import
  Images/Main menu/AI_background_crt_computer.jpg
  Images/Main menu/AI_background_crt_computer.jpg.import
  Images/Main menu/AI_bloody_background.jpg
  Images/Main menu/AI_title_background.jpg
  Images/Main menu/AI_title_background.jpg.import
  Images/Main menu/AI_title_background2.jpg.import
  ItemProtosets.tres
  Main_menu_buttons.tres
  Scenes/ContentManager/ModMaintenance/modmaintenance.tscn
  Scenes/ContentManager/OtherTools/overmap_grid_visualization.tscn
  Scenes/ContentManager/addremovemods.tscn
  Scenes/ContentManager/content_list.tscn
  Scenes/ContentManager/contenteditor.tscn
  Scenes/ContentManager/contentmanager.tscn
  Scenes/ContentManager/modmanager.tscn
  Scenes/ContentManager/othertools.tscn
  Scenes/GameOver.tscn
  Scenes/LoadingScreen.tscn
  Scenes/UI/EscapeMenu.tscn
  Scenes/UI/options_menu/audio/audio_options_menu.tscn
  Scenes/UI/options_menu/master_options_menu_with_tabs.tscn
  documentation.tscn
  scene_selector.tscn
Labels: enhancement

#755 Fix itemgroup crash
  Scripts/Gamedata/DItemgroups.gd
Labels: bug

#763 Update features list in readme
  FeatureList.md
  Media/Dimensionfall_add_remove_mod_menu.png
  Media/Dimensionfall_add_remove_mod_menu.png.import
  Media/Dimensionfall_main_menu.png
  Sounds/SFX/sfx.gd
Labels: documentation

#770 Move mob down by .5
  Scripts/Chunk.gd
  Scripts/OvermapGrid.gd
Labels: bug

#771 Fix container sprites on furniture
  Scripts/FurnitureBlueprintSrv.gd
  Scripts/FurnitureStaticSrv.gd
  Scripts/gamedata.gd
Labels: bug
